//! Linux Offline System Configuration Engine.
//!
//! Generates target configuration files for bare-metal offline Linux installations:
//! - `/etc/fstab` mounting EFI system partition, boot, root, and swap by UUID / PARTUUID.
//! - `/etc/hostname`, `/etc/locale.gen`, `/etc/vconsole.conf`, and `/etc/os-release`.
//! - `/etc/passwd`, `/etc/shadow`, and `/etc/group` for initial root and non-root user setup.

use crate::error::{Error, Result};
use std::fmt::Write as _;
use std::path::Path;

/// A single entry in `/etc/fstab`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FstabEntry {
    /// Device identifier, typically `UUID=<uuid>` or `PARTUUID=<partuuid>`.
    pub device: String,
    /// Mount point directory path (e.g. `/`, `/boot/efi`, `none` for swap).
    pub mount_point: String,
    /// Filesystem type (e.g. `ext4`, `vfat`, `swap`, `btrfs`, `xfs`).
    pub fs_type: String,
    /// Comma-separated mount options (e.g. `defaults,noatime`).
    pub options: String,
    /// Dump frequency (typically 0).
    pub dump: u8,
    /// Pass number for fsck check order (1 for root, 2 for other filesystems, 0 for ESP/swap).
    pub pass: u8,
}

impl FstabEntry {
    /// Formats this entry as a standard `/etc/fstab` single line.
    ///
    /// # Returns
    ///
    /// Tab-separated line representation.
    #[must_use]
    pub fn to_line(&self) -> String {
        format!(
            "{:<42} {:<16} {:<10} {:<24} {} {}",
            self.device, self.mount_point, self.fs_type, self.options, self.dump, self.pass
        )
    }
}

/// Generator for complete `/etc/fstab` configuration files.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct FstabGenerator {
    /// Accumulated filesystem mount entries.
    entries: Vec<FstabEntry>,
}

impl FstabGenerator {
    /// Creates a new [`FstabGenerator`].
    ///
    /// # Returns
    ///
    /// A new generator instance.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            entries: Vec::new(),
        }
    }

    /// Adds a filesystem mount entry.
    ///
    /// # Arguments
    ///
    /// * `entry` - Filesystem mount entry descriptor.
    pub fn add_entry(&mut self, entry: FstabEntry) {
        self.entries.push(entry);
    }

    /// Renders the complete `/etc/fstab` file text.
    ///
    /// # Returns
    ///
    /// Formatted content.
    #[must_use]
    pub fn render(&self) -> String {
        let mut out = String::from(
            "# /etc/fstab: static file system information.
",
        );
        out.push_str(
            "# Automatically generated by msi-rs bare-metal installer.
",
        );
        out.push_str(
            "#
",
        );
        out.push_str("# <file system>                            <mount point>    <type>     <options>                <dump> <pass>
");
        for entry in &self.entries {
            let _ = writeln!(out, "{}", entry.to_line());
        }
        out
    }
}

/// Offline user account specification for `/etc/passwd` and `/etc/shadow`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProvisionUserAccount {
    /// Username string (e.g. `root` or `admin`).
    pub username: String,
    /// User ID (0 for root, 1000+ for standard users).
    pub uid: u32,
    /// Group ID (0 for root, 1000+ for standard users).
    pub gid: u32,
    /// User full comment or display name (GECOS).
    pub gecos: String,
    /// Home directory path (e.g. `/root` or `/home/admin`).
    pub home_dir: String,
    /// Login shell binary path (e.g. `/bin/bash` or `/bin/sh`).
    pub shell: String,
    /// Password hash in crypt format (e.g. `$6$...` for SHA-512) or `!` to lock.
    pub password_hash: String,
}

/// Generator for `/etc/passwd`, `/etc/shadow`, and `/etc/group`.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct UserProvisioningEngine {
    /// Accumulated provisioned user accounts.
    users: Vec<ProvisionUserAccount>,
}

impl UserProvisioningEngine {
    /// Creates a new [`UserProvisioningEngine`].
    ///
    /// # Returns
    ///
    /// A new instance.
    #[must_use]
    pub const fn new() -> Self {
        Self { users: Vec::new() }
    }

    /// Adds an account for provisioning.
    ///
    /// # Arguments
    ///
    /// * `user` - User account specification.
    pub fn add_user(&mut self, user: ProvisionUserAccount) {
        self.users.push(user);
    }

    /// Renders `/etc/passwd`.
    ///
    /// # Returns
    ///
    /// Formatted passwd file text.
    #[must_use]
    pub fn render_passwd(&self) -> String {
        let mut s = String::new();
        for u in &self.users {
            let _ = writeln!(
                s,
                "{}:x:{}:{}:{}:{}:{}",
                u.username, u.uid, u.gid, u.gecos, u.home_dir, u.shell
            );
        }
        s
    }

    /// Renders `/etc/shadow`.
    ///
    /// # Returns
    ///
    /// Formatted shadow file text.
    #[must_use]
    pub fn render_shadow(&self) -> String {
        let mut s = String::new();
        for u in &self.users {
            // format: username:password_hash:last_changed:min:max:warn:inactive:expire:reserved
            let _ = writeln!(s, "{}:{}:19500:0:99999:7:::", u.username, u.password_hash);
        }
        s
    }

    /// Renders `/etc/group`.
    ///
    /// # Returns
    ///
    /// Formatted group file text.
    #[must_use]
    pub fn render_group(&self) -> String {
        let mut s = String::new();
        for u in &self.users {
            let _ = writeln!(s, "{}:x:{}:", u.username, u.gid);
        }
        s
    }
}

/// Linux machine identity and localization configuration settings.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LinuxIdentityConfig {
    /// System hostname.
    pub hostname: String,
    /// Primary system locale (e.g. `en_US.UTF-8`).
    pub locale: String,
    /// Virtual console keymap (e.g. `us`).
    pub keymap: String,
    /// Target operating system display name.
    pub os_name: String,
    /// Target operating system version.
    pub os_version: String,
}

impl LinuxIdentityConfig {
    /// Writes all identity files into the target sysroot hierarchy.
    ///
    /// # Arguments
    ///
    /// * `sysroot` - Filesystem root path of target Linux installation.
    ///
    /// # Errors
    ///
    /// Returns [`Error::SysrootMountError`] if writing identity files fails.
    pub fn write_to_sysroot(&self, sysroot: &Path) -> Result<()> {
        let etc = sysroot.join("etc");
        if let Err(e) = std::fs::create_dir_all(&etc) {
            return Err(Error::SysrootMountError {
                path: etc.display().to_string(),
                reason: format!("failed to create /etc directory: {e}"),
            });
        }

        // 1. /etc/hostname
        let hostname_path = etc.join("hostname");
        if let Err(e) = std::fs::write(
            &hostname_path,
            format!(
                "{}
",
                self.hostname
            ),
        ) {
            return Err(Error::SysrootMountError {
                path: hostname_path.display().to_string(),
                reason: format!("failed to write /etc/hostname: {e}"),
            });
        }

        // 2. /etc/vconsole.conf
        let vconsole_path = etc.join("vconsole.conf");
        let vconsole_content = format!(
            "KEYMAP={}
FONT=eurlatgr
",
            self.keymap
        );
        if let Err(e) = std::fs::write(&vconsole_path, vconsole_content) {
            return Err(Error::SysrootMountError {
                path: vconsole_path.display().to_string(),
                reason: format!("failed to write /etc/vconsole.conf: {e}"),
            });
        }

        // 3. /etc/locale.gen and /etc/locale.conf
        let locale_gen_path = etc.join("locale.gen");
        let locale_gen_content = format!(
            "{} UTF-8
",
            self.locale
        );
        let _ = std::fs::write(&locale_gen_path, locale_gen_content);

        let locale_conf_path = etc.join("locale.conf");
        let locale_conf_content = format!(
            "LANG={}
",
            self.locale
        );
        let _ = std::fs::write(&locale_conf_path, locale_conf_content);

        // 4. /etc/os-release
        let os_release_path = etc.join("os-release");
        let mut os_release = String::new();
        let _ = writeln!(os_release, r#"NAME="{}""#, self.os_name);
        let _ = writeln!(os_release, r#"VERSION="{}""#, self.os_version);
        let _ = writeln!(os_release, "ID=msi-os");
        let _ = writeln!(
            os_release,
            r#"PRETTY_NAME="{} {}""#,
            self.os_name, self.os_version
        );
        if let Err(e) = std::fs::write(&os_release_path, os_release) {
            return Err(Error::SysrootMountError {
                path: os_release_path.display().to_string(),
                reason: format!("failed to write /etc/os-release: {e}"),
            });
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Tests `/etc/fstab` generation.
    #[test]
    fn test_fstab_generator() {
        let mut gen = FstabGenerator::new();
        gen.add_entry(FstabEntry {
            device: "UUID=1234-ABCD".to_string(),
            mount_point: "/boot/efi".to_string(),
            fs_type: "vfat".to_string(),
            options: "umask=0077".to_string(),
            dump: 0,
            pass: 2,
        });
        gen.add_entry(FstabEntry {
            device: "UUID=5678-EFGH".to_string(),
            mount_point: "/".to_string(),
            fs_type: "ext4".to_string(),
            options: "defaults,noatime".to_string(),
            dump: 0,
            pass: 1,
        });

        let rendered = gen.render();
        assert!(rendered.contains("UUID=1234-ABCD"));
        assert!(rendered.contains("/boot/efi"));
        assert!(rendered.contains("UUID=5678-EFGH"));
        assert!(rendered.contains("ext4"));
    }

    /// Tests `/etc/passwd`, `/etc/shadow`, and `/etc/group` rendering.
    #[test]
    fn test_user_provisioning_engine() {
        let mut engine = UserProvisioningEngine::new();
        engine.add_user(ProvisionUserAccount {
            username: "root".to_string(),
            uid: 0,
            gid: 0,
            gecos: "Superuser".to_string(),
            home_dir: "/root".to_string(),
            shell: "/bin/bash".to_string(),
            password_hash: "$6$rounds=50000$saltsalt$hashedpassword".to_string(),
        });
        engine.add_user(ProvisionUserAccount {
            username: "admin".to_string(),
            uid: 1000,
            gid: 1000,
            gecos: "Administrator".to_string(),
            home_dir: "/home/admin".to_string(),
            shell: "/bin/bash".to_string(),
            password_hash: "$6$rounds=50000$saltsalt$adminpassword".to_string(),
        });

        let passwd = engine.render_passwd();
        assert!(passwd.contains("root:x:0:0:Superuser:/root:/bin/bash"));
        assert!(passwd.contains("admin:x:1000:1000:Administrator:/home/admin:/bin/bash"));

        let shadow = engine.render_shadow();
        assert!(shadow.contains("root:$6$rounds=50000$saltsalt$hashedpassword:19500:0:99999:7:::"));
        assert!(shadow.contains("admin:$6$rounds=50000$saltsalt$adminpassword:19500:0:99999:7:::"));

        let group = engine.render_group();
        assert!(group.contains("root:x:0:"));
        assert!(group.contains("admin:x:1000:"));
    }

    /// Tests writing identity files to sysroot.
    #[test]
    fn test_linux_identity_config_write() {
        let temp_dir =
            std::env::temp_dir().join(format!("msi_test_identity_{}", std::process::id()));
        let config = LinuxIdentityConfig {
            hostname: "installer-node".to_string(),
            locale: "en_US.UTF-8".to_string(),
            keymap: "us".to_string(),
            os_name: "Test Linux".to_string(),
            os_version: "1.0".to_string(),
        };

        assert!(config.write_to_sysroot(&temp_dir).is_ok());

        let hostname = std::fs::read_to_string(temp_dir.join("etc/hostname")).unwrap_or_default();
        assert_eq!(hostname.trim(), "installer-node");

        let vconsole =
            std::fs::read_to_string(temp_dir.join("etc/vconsole.conf")).unwrap_or_default();
        assert!(vconsole.contains("KEYMAP=us"));

        let os_rel = std::fs::read_to_string(temp_dir.join("etc/os-release")).unwrap_or_default();
        assert!(os_rel.contains(r#"NAME="Test Linux""#));
        assert!(os_rel.contains(r#"VERSION="1.0""#));

        let _ = std::fs::remove_dir_all(&temp_dir);
    }

    /// Tests error paths for writing identity files.
    #[test]
    fn test_linux_identity_config_errors() {
        let temp_dir = std::env::temp_dir().join(format!("msi_test_id_err_{}", std::process::id()));
        let _ = std::fs::create_dir_all(&temp_dir);

        let config = LinuxIdentityConfig {
            hostname: "installer-node".to_string(),
            locale: "en_US.UTF-8".to_string(),
            keymap: "us".to_string(),
            os_name: "Test Linux".to_string(),
            os_version: "1.0".to_string(),
        };

        // 1. etc is a file, create_dir_all fails
        let etc_file = temp_dir.join("etc");
        let _ = std::fs::write(&etc_file, b"not a dir");
        assert!(config.write_to_sysroot(&temp_dir).is_err());
        let _ = std::fs::remove_file(&etc_file);

        // 2. etc exists, but hostname is a directory, write fails
        let etc_dir = temp_dir.join("etc");
        let _ = std::fs::create_dir_all(&etc_dir);
        let hostname_dir = etc_dir.join("hostname");
        let _ = std::fs::create_dir_all(&hostname_dir);
        assert!(config.write_to_sysroot(&temp_dir).is_err());
        let _ = std::fs::remove_dir_all(&hostname_dir);

        // 3. hostname succeeds, but vconsole.conf is a directory, write fails
        let vconsole_dir = etc_dir.join("vconsole.conf");
        let _ = std::fs::create_dir_all(&vconsole_dir);
        assert!(config.write_to_sysroot(&temp_dir).is_err());
        let _ = std::fs::remove_dir_all(&vconsole_dir);

        // 4. vconsole succeeds, but os-release is a directory, write fails
        let os_rel_dir = etc_dir.join("os-release");
        let _ = std::fs::create_dir_all(&os_rel_dir);
        assert!(config.write_to_sysroot(&temp_dir).is_err());
        let _ = std::fs::remove_dir_all(&os_rel_dir);

        let _ = std::fs::remove_dir_all(&temp_dir);
    }
}
