repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt (auto-format and check)
        entry: python3 scripts/pre_commit.py fmt
        language: system
        pass_filenames: false
        always_run: true

      - id: cargo-build
        name: cargo build
        entry: python3 scripts/pre_commit.py build
        language: system
        pass_filenames: false
        always_run: true

      - id: cargo-clippy
        name: cargo clippy
        entry: python3 scripts/pre_commit.py clippy
        language: system
        pass_filenames: false
        always_run: true

      - id: cargo-test
        name: cargo test
        entry: python3 scripts/pre_commit.py test
        language: system
        pass_filenames: false
        always_run: true

      - id: update-shields
        name: update doc & test coverage shields in README.md
        entry: python3 scripts/pre_commit.py shields
        language: system
        pass_filenames: false
        always_run: true
