//! Native UI Abstraction and `MsiUserInterface` trait (`msi-ui-native`).
//!
//! Exposes a trait `MsiUserInterface` for external native wrappers (GTK, Qt, or Cocoa)
//! to intercept Dialog events if linked as a library, and for Windows/Wine native dialog templates.

use crate::error::Result;
use crate::ui::controls::ControlDefinition;
use crate::ui::engine::{DialogDefinition, UiEngine};
use crate::ui::events::{ControlEvent, DialogReturnCode};

/// Trait exposing MSI UI events for Native wrappers (GTK, Qt, Cocoa).
pub trait MsiUserInterface {
    /// Initialize the UI wrapper with the active engine.
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    fn initialize(&mut self, engine: &UiEngine) -> Result<()>;

    /// Display a dialog model modally or modelessly.
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    fn show_dialog(&mut self, dialog: &DialogDefinition) -> Result<DialogReturnCode>;

    /// Update control layout or properties within the active dialog.
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    fn update_control(&mut self, control: &ControlDefinition) -> Result<()>;

    /// Handle a generic control event generated by the engine.
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    fn handle_event(&mut self, event: &ControlEvent) -> Result<()>;
}

/// Fallback stubs for `USER32` dialog templates (`DLGTEMPLATE`), `CreateDialogIndirectParam`, `WM_COMMAND`, and `CreateFontIndirectW`.
pub mod user32_stubs {
    use super::{
        ControlDefinition, ControlEvent, DialogDefinition, DialogReturnCode, MsiUserInterface,
        Result, UiEngine,
    };

    /// Represents a `DLGTEMPLATE` stub.
    #[derive(Debug, Clone)]
    pub struct DlgTemplateStub {
        /// dialog
        _dialog: DialogDefinition,
    }

    impl DlgTemplateStub {
        /// Creates a new stub from a `DialogDefinition`.
        #[must_use]
        pub const fn new(dialog: DialogDefinition) -> Self {
            Self { _dialog: dialog }
        }
    }

    /// Windows USER32 fallback UI implementation.
    #[derive(Debug, Default)]
    pub struct WindowsUser32UI {
        /// templates
        templates: std::collections::HashMap<String, DlgTemplateStub>,
    }

    impl MsiUserInterface for WindowsUser32UI {
        /// # Errors
        ///
        /// Returns an error if the operation fails.
        fn initialize(&mut self, _engine: &UiEngine) -> Result<()> {
            Ok(())
        }

        /// # Errors
        ///
        /// Returns an error if the operation fails.
        fn show_dialog(&mut self, dialog: &DialogDefinition) -> Result<DialogReturnCode> {
            self.templates
                .insert(dialog.name.clone(), DlgTemplateStub::new(dialog.clone()));
            // Stubs `CreateDialogIndirectParam`
            Ok(DialogReturnCode::Return)
        }

        /// # Errors
        ///
        /// Returns an error if the operation fails.
        fn update_control(&mut self, _control: &ControlDefinition) -> Result<()> {
            // Stubs `CreateFontIndirectW` and standard SetWindowText
            Ok(())
        }

        /// # Errors
        ///
        /// Returns an error if the operation fails.
        fn handle_event(&mut self, _event: &ControlEvent) -> Result<()> {
            // Stubs `WM_COMMAND` processing
            Ok(())
        }
    }
}
