//! Native UI Abstraction and `MsiUserInterface` trait (`msi-ui-native`).
//!
//! Exposes a trait `MsiUserInterface` for external native wrappers (GTK, Qt, or Cocoa)
//! to intercept Dialog events if linked as a library, and for Windows/Wine native dialog templates.

use crate::error::Result;
use crate::ui::controls::ControlDefinition;
use crate::ui::engine::{DialogDefinition, UiEngine};
use crate::ui::events::{ControlEvent, DialogReturnCode};

/// Trait exposing MSI UI events for Native wrappers (GTK, Qt, Cocoa).
pub trait MsiUserInterface {
    /// Initialize the UI wrapper with the active engine.
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    ///
    /// # Arguments
    ///
    /// * `engine` - TODO: Document argument.
    ///
    /// # Returns
    ///
    /// TODO: Document return value.
    fn initialize(&mut self, engine: &UiEngine) -> Result<()>;

    /// Display a dialog model modally or modelessly.
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    ///
    /// # Arguments
    ///
    /// * `dialog` - TODO: Document argument.
    ///
    /// # Returns
    ///
    /// TODO: Document return value.
    fn show_dialog(&mut self, dialog: &DialogDefinition) -> Result<DialogReturnCode>;

    /// Update control layout or properties within the active dialog.
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    ///
    /// # Arguments
    ///
    /// * `control` - TODO: Document argument.
    ///
    /// # Returns
    ///
    /// TODO: Document return value.
    fn update_control(&mut self, control: &ControlDefinition) -> Result<()>;

    /// Handle a generic control event generated by the engine.
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    ///
    /// # Arguments
    ///
    /// * `event` - TODO: Document argument.
    ///
    /// # Returns
    ///
    /// TODO: Document return value.
    fn handle_event(&mut self, event: &ControlEvent) -> Result<()>;
}

/// Fallback stubs for `USER32` dialog templates (`DLGTEMPLATE`), `CreateDialogIndirectParam`, `WM_COMMAND`, and `CreateFontIndirectW`.
pub mod user32_stubs {
    use super::{
        ControlDefinition, ControlEvent, DialogDefinition, DialogReturnCode, MsiUserInterface,
        Result, UiEngine,
    };

    /// Represents a `DLGTEMPLATE` stub.
    #[derive(Debug, Clone)]
    pub struct DlgTemplateStub {
        /// dialog
        _dialog: DialogDefinition,
    }

    impl DlgTemplateStub {
        /// Creates a new stub from a `DialogDefinition`.
        ///
        /// # Arguments
        ///
        /// * `dialog` - TODO: Document argument.
        ///
        /// # Returns
        ///
        /// TODO: Document return value.
        #[must_use]
        pub const fn new(dialog: DialogDefinition) -> Self {
            Self { _dialog: dialog }
        }
    }

    /// Windows USER32 fallback UI implementation.
    #[derive(Debug, Default)]
    pub struct WindowsUser32UI {
        /// templates
        templates: std::collections::HashMap<String, DlgTemplateStub>,
    }

    impl MsiUserInterface for WindowsUser32UI {
        /// # Errors
        ///
        /// Returns an error if the operation fails.
        ///
        /// # Arguments
        ///
        /// * `_engine` - TODO: Document argument.
        ///
        /// # Returns
        ///
        /// TODO: Document return value.
        fn initialize(&mut self, _engine: &UiEngine) -> Result<()> {
            Ok(())
        }

        /// # Errors
        ///
        /// Returns an error if the operation fails.
        ///
        /// # Arguments
        ///
        /// * `dialog` - TODO: Document argument.
        ///
        /// # Returns
        ///
        /// TODO: Document return value.
        fn show_dialog(&mut self, dialog: &DialogDefinition) -> Result<DialogReturnCode> {
            self.templates
                .insert(dialog.name.clone(), DlgTemplateStub::new(dialog.clone()));
            // Stubs `CreateDialogIndirectParam`
            Ok(DialogReturnCode::Return)
        }

        /// # Errors
        ///
        /// Returns an error if the operation fails.
        ///
        /// # Arguments
        ///
        /// * `_control` - TODO: Document argument.
        ///
        /// # Returns
        ///
        /// TODO: Document return value.
        fn update_control(&mut self, _control: &ControlDefinition) -> Result<()> {
            // Stubs `CreateFontIndirectW` and standard SetWindowText
            Ok(())
        }

        /// # Errors
        ///
        /// Returns an error if the operation fails.
        ///
        /// # Arguments
        ///
        /// * `_event` - TODO: Document argument.
        ///
        /// # Returns
        ///
        /// TODO: Document return value.
        fn handle_event(&mut self, _event: &ControlEvent) -> Result<()> {
            // Stubs `WM_COMMAND` processing
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::user32_stubs::{DlgTemplateStub, WindowsUser32UI};
    use super::{ControlDefinition, ControlEvent, DialogDefinition, MsiUserInterface};
    use crate::execution::properties::EvaluationContext;
    use crate::ui::controls::ControlType;
    use crate::ui::engine::{UiEngine, DIALOG_ATTR_VISIBLE};

    use crate::ui::layout::DluRect;

    #[test]
    #[allow(clippy::redundant_clone)]
    fn test_windows_user32_ui() {
        let mut ui = WindowsUser32UI::default();
        assert!(format!("{ui:?}").contains("WindowsUser32UI"));
        let engine = UiEngine::new(EvaluationContext::new());

        assert!(ui.initialize(&engine).is_ok());

        let dialog = DialogDefinition {
            name: "TestDialog".to_string(),
            h_centering: 50,
            v_centering: 50,
            width: 200,
            height: 150,
            attributes: DIALOG_ATTR_VISIBLE,
            title: Some("Title".to_string()),
            control_first: "C1".to_string(),
            control_default: None,
            control_cancel: None,
        };

        let dialog_res = ui.show_dialog(&dialog);
        assert!(dialog_res.is_ok());

        let control = ControlDefinition::new(
            "TestDialog",
            "C1",
            ControlType::PushButton,
            DluRect::new(0, 0, 10, 10),
            3,
        );

        assert!(ui.update_control(&control).is_ok());

        let event = ControlEvent::new(
            "TestDialog",
            "C1",
            crate::ui::events::ControlEventType::Reset,
            None,
            1,
        );

        assert!(ui.handle_event(&event).is_ok());

        let stub = DlgTemplateStub::new(dialog.clone());
        let _stub_clone = stub.clone();
        assert!(format!("{stub:?}").contains("DlgTemplateStub"));
    }
}
