[package]
description = "msi-rs component"
repository = "https://github.com/example/msi-rs"
license = "MIT OR Apache-2.0"
readme = "../../README.md"
keywords = ["msi", "windows", "installer"]
categories = ["development-tools"]

name = "msi-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
msi = { path = "../msi" }
clap = { version = "4.4.11", features = ["derive", "cargo"] }

[dev-dependencies]
tempfile = "3.8.1"
