import os
from enum import IntEnum
from typing import Any, Callable, Dict, List, Optional, Tuple, Union

class MsiError(Exception): ...
class ValidationError(MsiError): ...
class DatabaseError(MsiError): ...
class CabinetError(MsiError): ...
class IoError(MsiError): ...
class WixError(MsiError): ...

class CompressionType(IntEnum):
    NONE = 0
    MSZIP = 1
    QUANTUM = 2
    LZX = 3

class ProductVersion:
    major: int
    minor: int
    build: int
    def __init__(self, major: int, minor: int, build: int = 0) -> None: ...
    @staticmethod
    def parse(version_str: str) -> ProductVersion: ...
    def as_tuple(self) -> Tuple[int, int, int]: ...
    def __lt__(self, other: ProductVersion) -> bool: ...
    def __le__(self, other: ProductVersion) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __gt__(self, other: ProductVersion) -> bool: ...
    def __ge__(self, other: ProductVersion) -> bool: ...

class Package:
    @staticmethod
    def open(path: Union[str, os.PathLike[str]]) -> Package: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Package: ...
    def save(self, path: Union[str, os.PathLike[str]]) -> None: ...
    def to_bytes(self) -> bytes: ...
    def get_property(self, name: str) -> Optional[str]: ...
    @property
    def properties(self) -> Dict[str, str]: ...
    @property
    def table_names(self) -> List[str]: ...
    def get_table(self, name: str) -> List[Dict[str, Any]]: ...
    def extract_cabinet(self, cabinet_name: str, destination_dir: Union[str, os.PathLike[str]]) -> List[str]: ...
    def __enter__(self) -> Package: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class PackageBuilder:
    def __init__(
        self,
        product_name: str,
        manufacturer: str,
        version: Union[str, Tuple[int, ...], ProductVersion],
        product_code: Optional[str] = None,
        upgrade_code: Optional[str] = None,
    ) -> None: ...
    def set_product_name(self, name: str) -> None: ...
    def set_manufacturer(self, mfr: str) -> None: ...
    def set_version(self, version: Union[str, Tuple[int, ...], ProductVersion]) -> None: ...
    def set_product_code(self, code: str) -> None: ...
    def set_upgrade_code(self, code: str) -> None: ...
    def add_property(self, name: str, value: str) -> None: ...
    def add_directory(
        self,
        dir_id: str,
        parent_id: Optional[str] = None,
        default_dir: str = ".",
    ) -> None: ...
    def add_component(
        self,
        comp_id: str,
        dir_id: str,
        comp_guid: Optional[str] = None,
        attributes: Optional[int] = None,
        condition: Optional[str] = None,
        keypath: Optional[str] = None,
    ) -> None: ...
    def add_feature(
        self,
        feat_id: str,
        parent_id: Optional[str] = None,
        title: Optional[str] = None,
        description: Optional[str] = None,
        display: Optional[int] = None,
        level: Optional[int] = None,
        dir_id: Optional[str] = None,
        attributes: Optional[int] = None,
    ) -> None: ...
    def add_feature_component(self, feat_id: str, comp_id: str) -> None: ...
    def add_file(
        self,
        file_id: str,
        comp_id: str,
        file_name: str,
        file_size: int,
        version: Optional[str] = None,
        language: Optional[str] = None,
        attributes: Optional[int] = None,
        sequence: Optional[int] = None,
    ) -> None: ...
    def add_media(
        self,
        disk_id: int,
        last_sequence: int,
        disk_prompt: Optional[str] = None,
        cabinet: Optional[str] = None,
        volume_label: Optional[str] = None,
        source: Optional[str] = None,
    ) -> None: ...
    def add_embedded_cabinet(self, name: str, data: bytes) -> None: ...
    def add_file_from_disk(
        self,
        source_path: Union[str, os.PathLike[str]],
        target_dir_id: str,
        feature_id: str,
        component_id: Optional[str] = None,
    ) -> str: ...
    def build(self) -> Package: ...
    def build_to_file(self, path: Union[str, os.PathLike[str]]) -> None: ...
    def build_to_bytes(self) -> bytes: ...
    def __enter__(self) -> PackageBuilder: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

def sanitize_identifier(name: str) -> str: ...

def build_msi(
    source_dir: Union[str, os.PathLike[str]],
    output_path: Union[str, os.PathLike[str]],
    *,
    product_name: str,
    version: Union[str, Tuple[int, ...], ProductVersion],
    manufacturer: str,
    product_code: Optional[str] = None,
    upgrade_code: Optional[str] = None,
    install_dir_name: Optional[str] = None,
    compression: CompressionType = CompressionType.MSZIP,
    progress_callback: Optional[Callable[[str, int, int], None]] = None,
) -> None: ...

def compile_wix(
    source: Union[str, os.PathLike[str]],
    output_path: Union[str, os.PathLike[str]],
    *,
    variables: Optional[Dict[str, str]] = None,
) -> None: ...

def inspect_msi(msi_path: Union[str, os.PathLike[str]]) -> Dict[str, Any]: ...
